### ISSUE TITLE
child_process: customFds option is deprecated, use stdio instead.

### ISSUE THREAD

**Issue by valtido** [sintaxi/harp#409]
I can't seem to install harp at all :( I tried older versions but same problem 

any idea what is going on ?
```
$ npm install harp -g
-
> node-sass@0.9.3 install c:\Users\vcaushi\nodejs\node_modules\harp\node_modules\terraform\node_modules\node-sass
> node build.js

child_process: customFds option is deprecated, use stdio instead.

c:\Users\vcaushi\nodejs\node_modules\harp\node_modules\terraform\node_modules\node-sass>node "c:\Users\vcaushi\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin
 rebuild
gyp ERR! configure error
gyp ERR! stack Error: spawn c:/Python273 ENOENT
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
gyp ERR! stack     at child_process.js:1137:20
gyp ERR! stack     at process._tickCallback (node.js:355:11)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Users\\vcaushi\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\vcaushi\nodejs\node_modules\harp\node_modules\terraform\node_modules\node-sass
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
Build failed
npm ERR! Error: ENOENT, lstat 'c:\Users\vcaushi\nodejs\node_modules\harp\node_modules\terraform\node_modules\less\test\less\errors\parse-error-missing-parens.less'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Users\\vcaushi\\nodejs\\node.exe" "c:\\Users\\vcaushi\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "harp" "-g"
npm ERR! cwd C:\Users\vcaushi
npm ERR! node -v v0.12.0
npm ERR! npm -v 1.4.16
npm ERR! path c:\Users\vcaushi\nodejs\node_modules\harp\node_modules\terraform\node_modules\less\test\less\errors\parse-error-missing-parens.less
npm ERR! fstream_path c:\Users\vcaushi\nodejs\node_modules\harp\node_modules\terraform\node_modules\less\test\less\errors\parse-error-missing-parens.less
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! fstream_stack c:\Users\vcaushi\AppData\Roaming\npm\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack FSReqWrap.oncomplete (evalmachine.<anonymous>:99:15)
npm ERR! node-sass@0.9.3 install: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@0.9.3 install script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Users\\vcaushi\\nodejs\\node.exe" "c:\\Users\\vcaushi\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "harp" "-g"
npm ERR! cwd C:\Users\vcaushi
npm ERR! node -v v0.12.0
npm ERR! npm -v 1.4.16
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\vcaushi\npm-debug.log
npm ERR! not ok code 0
/c/Users/vcaushi/AppData/Roaming/npm/npm: line 14:  5080 Signal 112              (core dumped) node "$basedir/node_modules/npm/bin/npm-cli.js" "$@"
```

**Comment by kevinsimper** [comment]
I think it is because you are using 0.12

If you want it to work, wait a little bit with 0.12 and use 0.10

**Comment by antipodeman** [comment]
I had the same problem. And I fixed it.	
Your problem here: "Error: spawn c:/Python273 ENOENT". 
See the section "Installation" on  https://github.com/TooTallNate/node-gyp and reinstall package with all dependies.

**Comment by valtido** [comment]
@antipodeman  Wish I never started that mate, now I am on a rabbit whole with hell of a lot of windows paradoxes I installed the SDK 7.1 when I install compiler it says I have not installed the SDK 7.1 like catch 22 there.

**Comment by kennethormandy** [comment]
Give it another try, we’re still getting this warning but the latest version should work fine on Windows and OS X:

```
npm install -g harp
```

**Comment by valtido** [comment]
It's working ... Thanks :)

**Comment by silentrob** [comment]
Accepting this issue as being fixed. Please reopen if you experience any other problems.
