### ISSUE TITLE
Error  libsass bindings not found

### ISSUE THREAD

**Issue by lafama** [sintaxi/harp#411]
```
/app/node_modules/harp/node_modules/terraform/node_modules/node-sass/lib/index.js:22
    throw new Error('`libsass` bindings not found. Try reinstalling `node-sass
          ^
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/app/node_modules/harp/node_modules/terraform/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/app/node_modules/harp/node_modules/terraform/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/app/node_modules/harp/node_modules/terraform/lib/stylesheet/processors/scss.js:1:74)
    at Module._compile (module.js:460:26)

```

**Comment by goloroden** [comment]
+1

**Comment by omichelsen** [comment]
Reinstalling harp (-g) fixed this for me.

**Comment by kennethormandy** [comment]
There was a release where this was causing problems for a day or two, but if you install the latest version it should be working now. Thanks for understanding!

```sh
npm install -g harp
```

**Comment by CryptexDHT** [comment]
Not yet

```
postinstall /.node/lib/node_modules/harp/node_modules/terraform/node_modules/node-sass
> node scripts/build.js

module.js:338                                                    
    throw err;                                                   
          ^                                                      
Error: Cannot find module '/.node/lib/node_modules/harp/node_modules/terraform/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'                                                   
    at Function.Module._resolveFilename (module.js:336:15)       
    at Function.Module._load (module.js:278:25)                  
    at Function.Module.runMain (module.js:501:10)                
    at startup (node.js:124:16)                                  
    at node.js:842:3 
```

**Comment by dylanpyle** [comment]
I'm seeing this with a fresh install - https://gist.github.com/dylanpyle/03b67648bb9598f02246

**Comment by d1b1** [comment]
on heroku the -g is not a solution. Any ideas? http://harpjs.com/docs/deployment/heroku for how to get this working on heroku.

**Comment by lafama** [comment]
I had this in the package.json file
``
{
  "name": "name",
  "version": "1.0.0",
  "description": "A Harp App on Heroku",
  "dependencies": {
    "harp": "0.15.0"
  },
  "engines": {
    "node": "0.10.x",
    "npm": "1.2.x"
  }
}
``
Setting the dependency to this version "harp": "0.15.0" removes this error
