### ISSUE TITLE
Error: `libsass` bindings not found when using iojs

### ISSUE THREAD

**Issue by Siecje** [sintaxi/harp#436]
When I try to use harp from the REPL or from the terminal I get an error about libsass.

As a workaround can you disable Sass if you are not using it?

``` JavaScript
> var h = require('harp');
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/home/siecje/Desktop/genesis/node_modules/harp/node_modules/terraform/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/home/siecje/Desktop/genesis/node_modules/harp/node_modules/terraform/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at Object.<anonymous> (/home/siecje/Desktop/genesis/node_modules/harp/node_modules/terraform/lib/stylesheet/processors/scss.js:1:74)
    at Module._compile (module.js:410:26)
```

**Comment by dwarcher** [comment]
getting this same error (Mac OSX)

**Comment by underr** [comment]
Same here.

**Comment by hastebrot** [comment]
Same error here.

**Workaround:** Remove array items `scss` and `sass` from `node_modules/harp/node_modules/terraform/lib/helpers/raw.js`.

~~~js
var processors = exports.processors = {
  "html": ["jade", "ejs", "md"],
  "css" : ["styl", "less"],
  "js"  : ["coffee"]
}
~~~

**Comment by hastebrot** [comment]
There is a branch that updates the `node-sass` dependency to a newer version, which also fixes this error.

I installed it with:

~~~
npm install -g https://github.com/sintaxi/terraform#release-v0.11.1
~~~

Related pull request: https://github.com/sintaxi/terraform/pull/94

**Comment by cfjedimaster** [comment]
Any update on this? I just got hit by it too.

**Comment by sintaxi** [comment]
Working on it now. Released new terraform this morning.  New release of harp is imminent. 

https://github.com/sintaxi/terraform/releases/tag/v0.12.0
