### ISSUE TITLE
font-awesome bower dependency causes compile to fail

### ISSUE THREAD

**Issue by darokel** [sintaxi/harp#489]
So I added `"fontawesome": "~4.4.0",` to my `bower.json` file and when I try to compile the project, I get the following error:

```
NameError: variable @fa-css-prefix is undefined
/Users/dkewal/Coding/Projects/Personal/mocha/gulpfile.js:32
    this.emit('end')
         ^

TypeError: this.emit is not a function
  at catchError (/Users/dkewal/Coding/Projects/Personal/mocha/gulpfile.js:32:7)
  at /Users/dkewal/Coding/Projects/Personal/mocha/gulpfile.js:96:4
  at /Users/dkewal/Coding/Projects/Personal/mocha/node_modules/harp/lib/index.js:250:11
  at /Users/dkewal/Coding/Projects/Personal/mocha/node_modules/harp/node_modules/async/lib/async.js:178:29
  at /Users/dkewal/Coding/Projects/Personal/mocha/node_modules/harp/lib/index.js:207:11
  at /Users/dkewal/Coding/Projects/Personal/mocha/node_modules/harp/node_modules/terraform/lib/stylesheet/index.js:59:23
  at /Users/dkewal/Coding/Projects/Personal/mocha/node_modules/harp/node_modules/terraform/lib/stylesheet/processors/less.js:23:21
  at /Users/dkewal/Coding/Projects/Personal/mocha/node_modules/harp/node_modules/terraform/node_modules/less/lib/less/render.js:33:38
  at /Users/dkewal/Coding/Projects/Personal/mocha/node_modules/harp/node_modules/terraform/node_modules/less/lib/less/parse.js:63:17
  at Object.finish [as _finish] (/Users/dkewal/Coding/Projects/Personal/mocha/node_modules/harp/node_modules/terraform/node_modules/less/lib/less/parser/parser.js:183:28)
  at Object.ImportVisitor._onSequencerEmpty (/Users/dkewal/Coding/Projects/Personal/mocha/node_modules/harp/node_modules/terraform/node_modules/less/lib/less/visitors/import-visitor.js:35:14)
  at ImportSequencer.tryRun (/Users/dkewal/Coding/Projects/Personal/mocha/node_modules/harp/node_modules/terraform/node_modules/less/lib/less/visitors/import-sequencer.js:50:14)
  at Object.ImportVisitor.run (/Users/dkewal/Coding/Projects/Personal/mocha/node_modules/harp/node_modules/terraform/node_modules/less/lib/less/visitors/import-visitor.js:29:25)
  at Object.Parser.parse (/Users/dkewal/Coding/Projects/Personal/mocha/node_modules/harp/node_modules/terraform/node_modules/less/lib/less/parser/parser.js:189:22)
  at Object.parse (/Users/dkewal/Coding/Projects/Personal/mocha/node_modules/harp/node_modules/terraform/node_modules/less/lib/less/parse.js:61:18)
  at Object.render (/Users/dkewal/Coding/Projects/Personal/mocha/node_modules/harp/node_modules/terraform/node_modules/less/lib/less/render.js:25:18)
  at Object.exports.compile (/Users/dkewal/Coding/Projects/Personal/mocha/node_modules/harp/node_modules/terraform/lib/stylesheet/processors/less.js:18:8)
  at /Users/dkewal/Coding/Projects/Personal/mocha/node_modules/harp/node_modules/terraform/lib/stylesheet/index.js:58:34
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

I checked the `font-awesome` stylesheets directly and can see that variable is definitely defined. What's weird is that I get the same error after I remove `font-awesome` all together.

**Comment by darokel** [comment]
Seems like any bower dependency with less files seems to cause the compiler to bork.
