### ISSUE TITLE
Promise is not defined on harp 0.20.1

### ISSUE THREAD

**Issue by vickydasta** [sintaxi/harp#525]
i got error bellow after sending GET request to harp server:

```
vickydasta@lab ~/dev/git $ harp server _harp
------------
Harp v0.20.1 – Chloi Inc. 2012–2015
Your server is listening at http://localhost:9000/
Press Ctl+C to stop the server
------------

/usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/postcss/lib/lazy-result.js:152
        this.processing = new Promise(function (resolve, reject) {
                              ^
ReferenceError: Promise is not defined
  at LazyResult.async (/usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/postcss/lib/lazy-result.js:152:31)
  at LazyResult.then (/usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/postcss/lib/lazy-result.js:75:21)
  at /usr/local/lib/node_modules/harp/node_modules/terraform/lib/stylesheet/index.js:64:44
  at /usr/local/lib/node_modules/harp/node_modules/terraform/lib/stylesheet/processors/less.js:24:14
  at /usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/less/lib/less/render.js:35:17
  at /usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/less/lib/less/parse.js:63:17
  at Object.finish [as _finish] (/usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/less/lib/less/parser/parser.js:183:28)
  at Object.ImportVisitor._onSequencerEmpty (/usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/less/lib/less/visitors/import-visitor.js:35:14)
  at ImportSequencer.tryRun (/usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/less/lib/less/visitors/import-sequencer.js:50:14)
  at Object.ImportVisitor.run (/usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/less/lib/less/visitors/import-visitor.js:29:25)
  at Object.Parser.parse (/usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/less/lib/less/parser/parser.js:189:22)
  at Object.parse (/usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/less/lib/less/parse.js:61:18)
  at Object.render (/usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/less/lib/less/render.js:25:18)
  at Object.exports.compile (/usr/local/lib/node_modules/harp/node_modules/terraform/lib/stylesheet/processors/less.js:18:8)
  at /usr/local/lib/node_modules/harp/node_modules/terraform/lib/stylesheet/index.js:58:34
  at fs.js:268:14
  at Object.oncomplete (fs.js:107:15)
```

**Comment by omichelsen** [comment]
You are probably running an old version of node. Harp now requires node 0.12+ (would recommend you at least upgrade to 4.2.4 LTS).

**Comment by vickydasta** [comment]
OK, i got that. 
i'll close this issue then, thanks by the way :)

**Comment by kennethormandy** [comment]
Sorry for the trouble. Yes, we dropped Node v0.10.x support as of [Harp v0.20.x](http://harpjs.com/blog/v0-20-0-node-5-compatibility) due to some of the preprocessors needing to be updated. Thanks for the response @omichelsen!
