### ISSUE TITLE
don't automatically parse *.js files

### ISSUE THREAD

**Issue by chharvey** [sintaxi/harp#561]
Harp seems to automatically parse javascript files, because when I inspect my page and look at the JS source, the file is minified and all the comments are removed.

This is a request to disable _automatic_ parsing, and make it an opt-in function for users who want it. Continue reading for my rationale.

When there's a syntax error in a Javascript file, harp crashes—see my error report below. This is not ideal, because it makes debugging much more difficult, and I have to restart the server (`$ harp server`) after every crash. I think a better solution instead would be to have the browser handle client-side javascript, as it does when the JS code lives in an internal `<script>` tag. That way even when the JS fails, the html is still rendered and the server keeps on spinning. In addition, the javascript code is much more transparent in the browser dev tools and debugging is much easier.

Examples using Jade:
- Inline script tag. Server works fine and doesn't crash, but JS fails (as expected) when browser reloads.
  
  ``` jade
  //- page.jade
  script.
    function double(x) { rturn 2*x; } // intentional syntax error
    console.log(double(3));
  ```
- External script file. Server crashes and browser doesn't even load anything.
  
  ``` jade
  //- page.jade
  script(src="script.js")
  ```
  
  ``` javascript
  // script.js
  function double(x) { rturn 2*x; } // intentional syntax error
  console.log(double(3));
  ```

Here's the error report I'm getting:

<details>
  <summary>

stack trace</summary>

```
undefined:1534
    throw new JS_Parse_Error(message, filename, line, col, pos);
    ^
Error
  at new JS_Parse_Error (<anonymous>:1526:18)
  at js_error (<anonymous>:1534:11)
  at croak (<anonymous>:2025:9)
  at token_error (<anonymous>:2033:9)
  at unexpected (<anonymous>:2039:9)
  at semicolon (<anonymous>:2059:43)
  at simple_statement (<anonymous>:2239:73)
  at eval (<anonymous>:2112:19)
  at eval (<anonymous>:2072:24)
  at block_ (<anonymous>:2352:20)
  at eval (<anonymous>:2325:25)
  at function_ (<anonymous>:2330:15)
  at expr_atom (<anonymous>:2538:24)
  at maybe_unary (<anonymous>:2708:19)
  at expr_ops (<anonymous>:2743:24)
  at maybe_conditional (<anonymous>:2748:20)
  at maybe_assign (<anonymous>:2772:20)
  at expression (<anonymous>:2791:20)
  at expr_list (<anonymous>:2557:24)
  at subscripts (<anonymous>:2691:30)
  at subscripts (<anonymous>:2668:20)
  at subscripts (<anonymous>:2688:20)
  at expr_atom (<anonymous>:2544:20)
  at maybe_unary (<anonymous>:2708:19)
  at expr_ops (<anonymous>:2743:24)
  at maybe_conditional (<anonymous>:2748:20)
  at maybe_assign (<anonymous>:2772:20)
  at expression (<anonymous>:2791:20)
  at simple_statement (<anonymous>:2239:55)
  at eval (<anonymous>:2112:19)
  at eval (<anonymous>:2072:24)
  at block_ (<anonymous>:2352:20)
  at eval (<anonymous>:2119:29)
  at eval (<anonymous>:2072:24)
  at if_ (<anonymous>:2338:21)
  at eval (<anonymous>:2163:24)
  at eval (<anonymous>:2072:24)
  at block_ (<anonymous>:2352:20)
  at eval (<anonymous>:2325:25)
  at function_ (<anonymous>:2330:15)
  at eval (<anonymous>:2160:24)
  at eval (<anonymous>:2072:24)
  at eval (<anonymous>:2819:23)
  at Object.parse (<anonymous>:2829:7)
  at /Users/Chris/.npm-global/lib/node_modules/harp/node_modules/uglify-js/tools/node.js:61:33
  at Array.forEach (native)
  at Object.exports.minify (/Users/Chris/.npm-global/lib/node_modules/harp/node_modules/uglify-js/tools/node.js:56:15)
  at Function.exports.js.exports.javascript (/Users/Chris/.npm-global/lib/node_modules/harp/node_modules/harp-minify/lib/index.js:34:17)
  at /Users/Chris/.npm-global/lib/node_modules/harp/node_modules/terraform/lib/javascript/index.js:58:25
  at Object.exports.compile (/Users/Chris/.npm-global/lib/node_modules/harp/node_modules/terraform/lib/javascript/processors/js.js:2:2)
  at render (/Users/Chris/.npm-global/lib/node_modules/harp/node_modules/terraform/lib/javascript/index.js:52:23)
  at /Users/Chris/.npm-global/lib/node_modules/harp/node_modules/terraform/lib/javascript/index.js:101:7
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

</details>

**Comment by chharvey** [comment]
related: https://github.com/sintaxi/harp/issues/54

**Comment by sintaxi** [comment]
This behaviour changed. Install harp@next to try it out.

**Comment by sintaxi** [comment]
As before, `.js` are no longer processed.
