### ISSUE TITLE
Error installing/updating harp with npm updated

### ISSUE THREAD

**Issue by NetLancer** [sintaxi/harp#608]
Hi there! Generally it does not install (since i've got npm updated: on debian8 - npm --version 5.02, on ubuntu lts - npm --version 5). Yes, i've tried to get it working on both linuxes. But before it worked fine. Don't know if it is about harp recent update or npm but generally issue resembles #606, and here what it says now (sudo npm install -g harp):

user@debian:~$ harp --version
fs.js:896
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^
Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/harp/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:896:18)
    at Object.getInstalledBinaries (/usr/local/lib/node_modules/harp/node_modules/node-sass/lib/extensions.js:124:13)
    at foundBinariesList (/usr/local/lib/node_modules/harp/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/usr/local/lib/node_modules/harp/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/usr/local/lib/node_modules/harp/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/usr/local/lib/node_modules/harp/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/harp/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

I'm not a node.js developer and a novice in harp, plse help

**Comment by Nadeeshyama** [comment]
I'm having problems with Harp on a more recent version of Node as well. Is this project abandoned?

**Comment by sintaxi** [comment]
@Nadeeshyama there was a release last Friday https://github.com/sintaxi/harp/releases/tag/v0.24.0

@NetLancer thanks for reporting the issue. what version of node are you running?

**Comment by Nadeeshyama** [comment]
Thanks @sintaxi.

**Comment by bernardodsanderson** [comment]
I'm having the same issue, node v7.10.0

**Comment by Erowlin** [comment]
Bump, same issue over there

**Comment by Nadeeshyama** [comment]
Working for me now. I did a clean install.

**Comment by LuisP89** [comment]
First error: I can only install it if I execute "sudo su" before.
Second error: Same error as @bernardodsanderson
 
S.O. Ubuntu 16.04
node -v: v8.7.0
npm -v: 5.4.2

**Comment by hd719** [comment]
Hello all this worked for me, in your home directory run this command, basically I was getting this error because my root did not have the correct access rights (https://github.com/nodejs/node-gyp/issues/454)

`sudo npm install --unsafe-perm --verbose -g harp`

**Comment by EskoCruz** [comment]
It is a permissions problem caused by using `sudo`.
Just `sudo` uninstall harp and reinstall it without `sudo`.

Uninstall harp:
`sudo npm uninstall -g harp`

Reinstall harp:
`npm install -g harp`

Now I can check if installed correctly by checking the version:
`harp -V` or `harp version`

---
macOS High Sierra 10.13.3
node -v: v9.5.0
npm -v: 5.6.0

**Comment by oshybrid** [comment]
I still error out, but now it gives a…

In file included from ../src/binding.cpp:3:
../src/sass_context_wrapper.h:8:10: fatal error: 'sass/context.h' file not found
#include <sass/context.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/harp/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/harp/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/local/lib/node_modules/harp/node_modules/node-sass
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bradhutchins/.npm/_logs/2018-02-05T19_05_26_146Z-debug.log
$

Brad Hutchins

**Comment by EskoCruz** [comment]
@oshybrid - Do you have **libsass** installed.
If you are using homebrew, run 
`brew install libsass`

**Comment by oshybrid** [comment]
Though I did,

But I reinstalled.

Still getting error but it changed.



../src/sass_types/list.cpp:29:19: error: no matching function for call to
      'sass_make_list'
    return *out = sass_make_list(length, comma ? SASS_COMMA : SASS_SPACE...
                  ^~~~~~~~~~~~~~
/usr/local/include/sass/values.h:53:34: note: candidate function not viable:
      requires 2 arguments, but 3 were provided
ADDAPI union Sass_Value* ADDCALL sass_make_list    (size_t len, enum Sas...
                                 ^
1 error generated.
make: *** [Release/obj.target/binding/src/sass_types/list.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/harp/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/harp/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/local/lib/node_modules/harp/node_modules/node-sass
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bradhutchins/.npm/_logs/2018-02-07T14_18_22_116Z-debug.log
$

Brad Hutchins

**Comment by GaragusoPD** [comment]
Same issue here, on **ubuntu 16.04, node 9.8** and **npm 5.8**. What worked for me was this line:

`sudo npm install --unsafe-perm --verbose -g harp`

**Comment by schutzsmith** [comment]
Uninstalling as sudo and then reinstalling normally worked. Thanks @EskoCruz!

**Comment by JordanSchuetz** [comment]
> Hello all this worked for me, in your home directory run this command, basically I was getting this error because my root did not have the correct access rights ([nodejs/node-gyp#454](https://github.com/nodejs/node-gyp/issues/454))
> 
> I am on node version `8.6.0`
> 
> `sudo npm install --unsafe-perm --verbose -g harp`

Dude thank you so much this worked for me!
