### ISSUE TITLE
Error: ENOENT: no such file or directory...

### ISSUE THREAD

**Issue by kuakeli** [sintaxi/harp#626]
High Sierra
node v9.4.0
npm v5.6.0
latest harp with node-sass v4.7.2

Any Harp command gives this:
```
fs.js:924
  return binding.readdir(pathModule.toNamespacedPath(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/harp/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:924:18)
    at Object.getInstalledBinaries (/usr/local/lib/node_modules/harp/node_modules/node-sass/lib/extensions.js:128:13)
    at foundBinariesList (/usr/local/lib/node_modules/harp/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/usr/local/lib/node_modules/harp/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/usr/local/lib/node_modules/harp/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/usr/local/lib/node_modules/harp/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/harp/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
```

What should I do to fix this?

**Comment by nonodev96** [comment]
Try to install as root, unsafe-perm and global
`sudo npm install --unsafe-perm -g node-sass`
