### ISSUE TITLE
`harp init myproject` doesn't work

### ISSUE THREAD

**Issue by Hatko** [sintaxi/harp#631]
I have macOS High Sierra 10.13.3
I installed harp by [this tutorial](http://harpjs.com/docs/environment/install). When I try to run `harp init myproject` I get the next error:

```
fs.js:924
  return binding.readdir(pathModule.toNamespacedPath(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir 'path/.nvm/versions/node/v9.5.0/lib/node_modules/harp/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:924:18)
    at Object.getInstalledBinaries (path/.nvm/versions/node/v9.5.0/lib/node_modules/harp/node_modules/node-sass/lib/extensions.js:128:13)
    at foundBinariesList (path/.nvm/versions/node/v9.5.0/lib/node_modules/harp/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (path/.nvm/versions/node/v9.5.0/lib/node_modules/harp/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (path/.nvm/versions/node/v9.5.0/lib/node_modules/harp/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (path/.nvm/versions/node/v9.5.0/lib/node_modules/harp/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (path/.nvm/versions/node/v9.5.0/lib/node_modules/harp/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
```

Am I doing something wrong?

**Comment by Hatko** [comment]
Fixed by reinstalling
